# Generated by Django 3.1.5 on 2021-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20210117_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
