# Generated by Django 3.1.5 on 2021-02-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('res1', models.CharField(blank=True, max_length=250)),
                ('res2', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('res1', models.CharField(blank=True, max_length=250)),
                ('res2', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('price', models.PositiveIntegerField(blank=True)),
                ('discount', models.PositiveIntegerField()),
                ('discount_image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('res1', models.CharField(blank=True, max_length=250)),
                ('res2', models.CharField(blank=True, max_length=250)),
                ('res3', models.CharField(blank=True, max_length=250)),
                ('res4', models.CharField(blank=True, max_length=250)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.brandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.categorymodel')),
            ],
        ),
    ]
