# Generated by Django 3.1.5 on 2021-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearmodel',
            name='discount',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wearmodel',
            name='discount_image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
